### ISSUE TITLE
Numeric input method

### ISSUE THREAD

**Issue by Chris5-11** [JaiPizGon/NeuralSens#1]
As mentioned, there is an additional method to use numeric input to describe the weight of the model. Could u give an example in applying this method with numeric input because I had built a model with keras.

**Comment by JaiPizGon** [comment]
Sorry for the delay, you can see an example of how to do it in https://arxiv.org/abs/2002.11423 

You have an example on how to use the package with keras in the annex.

Check if that works for you and reach out again with any errors.

Thanks for using the package!
