### ISSUE TITLE
Attribute Error: Unexpected keyword argument 'legend

### ISSUE THREAD

**Issue by LaxminarayanSid** [JaiPizGon/NeuralSens#26]
Running the python example given in the readme threw an attribute error: Rectangle.set() got an unexpected keyword argument 'legend'
![image](https://github.com/user-attachments/assets/919418cb-1ac5-4689-bfeb-4d5063ebbfa9)

**Comment by JaiPizGon** [comment]
Hi!

I have just tried the code provided in the README and works perfectly, could you provide the versions of the package you have installed in order to reproduce the error? (pip list)

Thanks.
